apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - eventlisteners/el_github-event.yaml
  - triggerbindings/github-pr.yaml
  - triggerbindings/github-push.yaml
  - triggertemplates/github-build-deploy.yaml
  - triggertemplates/github-tag-delete.yaml
  - pipelines/github-build-deploy.yaml
  - pipelines/github-tag-delete.yaml
  - tasks/validate-gitbranch.yaml
  - tasks/validate-gitflow.yaml
  - tasks/clone-github-repo.yaml
  - tasks/build-image.yaml
  - tasks/test-and-build-go.yaml

