---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push
spec:
  params:
    - name: base 
      value: PUSH-NOBASE
    - name: head
      value: $(body.ref)  # e.g. refs/heads/feature/nia-238, release-0.1.2
    - name: repo-url
      value: $(body.repository.ssh_url)
    - name: repo-name
      value: $(body.repository.name)

