apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-tag-delete
spec:
  description: |
    This pipeline reacts to a "close" pull request from a feature, hotfix or
    release head. It deletes the deployment.

  params:
    # Images
    - name: python-image
      type: string
      description: The docker image with Python 3
      default: python:3.12.0-alpine

    # Deployment and services
    - name: deployment-name
      type: string
      description: The name of the deployment, service and DNS

  # -----------------------------------------------------
  tasks:
    - name: undeploy-image
      taskRef:
        name: kubernetes-actions  # From Tekton Hub
      params:
        - name: "script"
          value: |
            export DEPLOYMENT=$(params.deployment-name)

            kubectl version | grep 'Client Version'
            kubectl delete svc $DEPLOYMENT
            kubectl delete deployment/$DEPLOYMENT

