---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-event
spec:
  serviceAccountName: tekton-service-account
  triggers:
    - name: trigger-push-feature
      bindings:
        - ref: github-push
      template:
        ref: github-build-deploy
      interceptors:
        - name: "Only Pushes"
          ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["push"]
        - name: "Only Pull Requests from designated user"
          ref:
            name: "cel"
          params:
            - name: "CEL Filter: security stand-in due to Ngrok rewrite issues"
              value: "body.sender.login == 'PentheusLennuye'"
        - name: "CEL filter: Ignore pushes to delete"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.deleted == false"
        - name: "CEL filter: Ignore pushes into main and develop"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "!(body.pull_request.head.ref in ['develop', 'main'])"
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"

    # PULL REQUESTS ============================================================
    # Pull Request Open --------------------------------------------------------
    - name: trigger-pr
      bindings:
        - ref: github-pr
      template:
        ref: github-build-deploy
      interceptors:
        - name: "Only Pull Requests"
          ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "Only Pull Requests from designated user"
          ref:
            name: "cel"
          params:
            - name: "CEL Filter: security stand-in due to Ngrok rewrite issues"
              value: "body.sender.login == 'PentheusLennuye'"
        - name: "CEL filter: only opened PRs"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'reopened']"  # no synchronize
        - name: "CEL filter: Do not accept PRs from develop"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "!(body.pull_request.head.ref == 'develop')"
        - name: "CEL filter: Accept PRs only to develop and main"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.pull_request.base.ref in ['main', 'develop']"
            - name: "overlays"
              value:
                - key: head_branchname
                  expression: "body.pull_request.head.ref"
                - key: base_branchname
                  expression: "body.pull_request.base.ref"

    # Merged: i.e. Pull Request Closed and Merged is True ---------------------------
    - name: trigger-merge
      bindings:
        - ref: github-pr
      template:
        ref: github-tag-delete
      interceptors:
        - name: "Only Pull Requests"
          ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"]
        - name: "CEL filter: only closed PRs with merge set to true"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['closed'] && body.pull_request.merged == true"
        - name: "Only Pull Requests from designated user"
          ref:
            name: "cel"
          params:
            - name: "CEL Filter: security stand-in due to Ngrok rewrite issues"
              value: "body.sender.login == 'PentheusLennuye'"
        - name: "CEL filter: Do not accept PRs from develop or main"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "!(body.pull_request.head.ref in ['main', 'develop'])"
            - name: "overlays"
              value:
                - key: head_branchname
                  expression: "body.pull_request.head.ref"
                - key: base_branchname
                  expression: "body.pull_request.base.ref"

