---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-push
spec:
  serviceAccountName: tekton-service-account
  triggers:
    - name: trigger-push
      bindings:
        - ref: tb-github-pr
      template:
        ref: tt-github-pr-trigger-template
      interceptors:
        - name: "Pushes"
          ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "eventTypes"
              value: ["push"]
        - name: "Only Push Requests from designated user"
          ref:
            name: "cel"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "CEL Filter: security stand-in due to Ngrok rewrite issues"
              value: "body.sender.login == 'PentheusLennuye'"
        - name: "CEL filter: Do not accept Pushes into develop or main"
          ref:
            name: "cel"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "filter"
              value: "!(body.ref in ['refs/heads/main', 'refs/heads/develop'])"
