---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tt-github-remove-deployment
spec:
  params:
    - name: repo-url
    - name: repo-name
    - name: head
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: epl-remove-deployment-run-
    spec:
      serviceAccountName: tekton-kubectl-service-account
      pipelineRef:
        name: pl-remove-deployment
      workspaces:
        - name: git-credentials
          secret:
            secretName: git-machine-credentials
      params:
        - name: deployment-name
          value: $(tt.params.repo-name)
